name: Github actions for webapp

on:
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: rootpassword
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: testuser
                    MYSQL_PASSWORD: testpassword
                options: >-
                    --health-cmd="mysqladmin ping --silent" 
                    --health-interval=10s 
                    --health-timeout=5s 
                    --health-retries=3

        env:
            # Application to connect to MySQL.
            DB_NAME: test_db
            DB_USER: testuser
            DB_PASSWORD: testpassword
            DB_HOST: 127.0.0.1
            PORT: 8080

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install dependencies
              run: npm install

            - name: Wait for MySQL to be ready
              run: |
                  for i in {1..30}; do
                    nc -z $DB_HOST 3306 && break || sleep 1
                  done

            - name: Run tests
              run: npm test
